# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI - CPU ASAN Linux x86_64 -> Linux x86_64 tests. Max LLVM/sysroot

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  issues: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for main branch
  cancel-in-progress: ${{ github.ref != 'main' }}

jobs:
  get-runner:
    uses: ./.github/workflows/runner-linux-x86-64.yaml

  run-tests:
    name: "CPU ASAN Linux x86_64 -> Linux x86_64 tests. Max LLVM/sysroot. Runner ${{ matrix.job_info.runner }}"
    needs: get-runner
    if: always()
    runs-on: ${{ matrix.job_info.runner }}
    steps:
      - uses: actions/checkout@v5

      - run: echo "Building / running ASAN tests (max LLVM / sysroot)..."
      - run: bazel test --config=asan --repo_env=LLVM_VERSION=21 --repo_env=SYSROOT_DIST=linux_glibc_2_35 //cc/sanitizers/tests:all

      - run: echo "Bzlmod. Building / running tests (max LLVM / sysroot)..."
      - run: bazel test --config=asan --repo_env=LLVM_VERSION=21 --repo_env=SYSROOT_DIST=linux_glibc_2_35 --config=bzlmod //cc/sanitizers/tests:all